# Generated by Django 4.1.2 on 2022-12-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='all_occurrences',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
